apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
  labels: 
    app: color-api
spec:
  replicas: 6
  selector: 
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
        - name: color-api-pod
          image: vinispeed/color-api:1.2.1
          env:
            - name: API_PORT
              value: '8080'
            - name: DELAY_STARTUP
              value: "false"
            - name: FAIL_LIVENESS 
              value: "false"
            - name: FAIL_READINESS
              value: "true" 
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
          startupProbe:
            httpGet:
              path: /up
              port: 8080
            failureThreshold: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            failureThreshold: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: color-api-svc
spec:
  selector:
    app: color-api
  ports:
    - port: 80
      targetPort: 8080
