apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  labels: 
    name: traffic-gen
spec:
  containers:
    - name: traffic-gen
      image: vinispeed/traffic-gen:1.0.0
      args:
        - 'color-api-svc/hostname'
        - '0.5'
      env:
        - name: API_PORT
          value: '8080'
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: '500m'
          memory: '512Mi'
