apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  labels:
    name: traffic-gen
spec:
  containers:
    - name: traffic-gen
      image: vinispeed/traffic-gen:1.0.0
      args:
        - '10.244.0.72'
        - '0.5'
