apiVersion: v1
kind: Pod
metadata:
  name: color-backend
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
    - name: color-backend
      image: vinispeed/color-api:1.1.2
      ports:
        - containerPort: 8080
