# Example of Cross-Namespace service communication
apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  namespace: default
  labels:
    name: traffic-gen
spec:
  containers:
    - name: traffic-gen
      image: vinispeed/traffic-gen:1.0.0
      args:
        # fully qualified domain name
        - 'color-api-svc.dev.svc.cluster.local'
        - '1'
