# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "control" do |control|
    control.vm.box = "bento/fedora-40"
    control.vm.box_version = "202502.21.0"
    control.vm.network "private_network", ip: "192.168.56.100"
    # Exposes minikube dashboard
    control.vm.network "forwarded_port", guest: 42465, host: 42465, auto_correct: true
    control.vm.synced_folder "./data", "/vagrant_data", type: "rsync", rsync_auto: true
    control.vm.provider "virtualbox" do |vb|
       vb.memory = "4096"
       vb.cpus = 2
     end
    control.vm.provision "shell", path: "provision_control.sh"
  end

  # Kubernetes Worker Node
  config.vm.define "node_1" do |node_1|
    node_1.vm.box = "bento/fedora-40"
    node_1.vm.box_version = "202502.21.0"
    node_1.vm.network "private_network", ip: "192.168.56.101"
    # node_1.vm.synced_folder "../data", "/vagrant_data"
    node_1.vm.provider "virtualbox" do |vb|
       vb.memory = "4096"
       vb.cpus = 2
     end
    node_1.vm.provision "shell", path: "provision_node.sh"
  end

end
