apiVersion: v1
kind: Pod
metadata:
  name: color-backend
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
    - name: color-backend
      image: vinispeed/color-api:1.1.2
      resources:
        requests:
          cpu: '200m'
          memory: '256Mi'
        limits:
          cpu: '500m'
          memory: '512Mi'
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: color-api-svc
  namespace: dev
  labels:
    app: color-api
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
    - port: 80
      targetPort: 8080
